# -*- coding: utf-8 -*-
"""DATA VISUALIZATION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D9pYLXOobXTyoA7qUW_i0_i0Riwwcg1D
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

df= pd.read_csv('/content/heart.csv')

#EDA - EXPLORATORY DATA ANALYSIS

df.head(10)

df.tail(10)

df.shape

df.info()

df.describe()

#DATA VISUALIZATION - BASICS matplotlib.pyplot as plt
  #Types of plot to describe the diagrammatic representation of the dataframe

a=df['age']
plt.plot(a)

b=df['cp']
c=df['slope']
plt.scatter(b,c)

d=df['exang']
plt.hist(d)

e=df['target']
plt.bar(e,height=100,width=100)

f=df['trestbps']
plt.pie(f)